version: "3.8"

services:
  
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./src/services/frontend
      target: development
    volumes:
      - ./src/services/frontend/src:/app/src
    ports:
      - 3000:3000
